pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
        NODE_OPTIONS = '--openssl-legacy-provider'
        GITHUB_TOKEN = credentials('jenkins-github-token')
        GITHUB_REPOSITORY = 'jodyheryanto/a428-cicd-labs'
        PUBLIC_URL = 'https://jodyheryanto.github.io/a428-cicd-labs'
    }
    triggers {
        pollSCM('H/2 * * * *')
    }
    stages {
        stage('Setup') {
            steps {
                sh 'apt-get update && apt-get install -y git'
            }
        }
        stage('Clone Repository') {
            steps {
                git branch: 'react-app',
                    credentialsId: 'jenkins-github-token',
                    url: 'https://github.com/jodyheryanto/a428-cicd-labs.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the website? (Click "Proceed" to continue)'
                sh 'chmod +x ./jenkins/scripts/github-pages.sh && ./jenkins/scripts/github-pages.sh'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}