pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    triggers {
        pollSCM('H/2 * * * *')
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'react-app',
                    credentialsId: 'jenkins-github-token',
                    url: 'https://github.com/jodyheryanto/a428-cicd-labs.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the website? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}